/* Professional services — dental, legal, accounting, clinics, consultants.
   Calm, credible, appointment-led. Blue-teal reads as competent, not cold. */
module.exports = {
  key: 'professional',
  label: 'Professional & medical practice',
  fonts: 'family=Sora:wght@600;700&family=Source+Sans+3:wght@400;500;600;700',
  tokens: {
    '--font-head': '"Sora",system-ui,sans-serif',
    '--font-body': '"Source Sans 3",system-ui,sans-serif',
    '--head-weight': '600',
    '--fs-body': '1.05rem',
    '--bg': '#ffffff',
    '--ink': '#2b3742',
    '--ink-strong': '#12202c',
    '--ink-soft': '#4c5b68',
    '--ink-mute': '#5c6b78',
    '--accent': '#0f6d80',
    '--accent-hover': '#0b5665',
    '--accent-ink': '#0d6274',
    '--accent-soft': '#e2f1f4',
    '--accent-ring': 'rgba(15,109,128,.24)',
    '--on-accent': '#ffffff',
    '--line': '#e3e9ee',
    '--line-strong': '#c7d2da',
    '--card-bg': '#ffffff',
    '--input-bg': '#ffffff',
    '--strip-bg': '#f3f7f9',
    '--shadow': '0 16px 44px -24px rgba(18,32,44,.32)',
    '--radius-btn': '8px',
    '--radius-card': '14px',
    '--radius-mark': '10px',
    '--radius-input': '8px',
    '--hero-bg': '#0d2733',
    '--hero-ink': '#f4fafb',
    '--hero-ink-soft': '#bed4db',
    '--hero-chip': 'rgba(255,255,255,.13)',
    '--hero-chip-ink': '#d7ecf1',
    '--hero-check': '#63c3d4',
    '--hero-art':
      'radial-gradient(720px 450px at 85% 10%,rgba(20,120,140,.5),transparent 65%),radial-gradient(500px 340px at 5% 90%,rgba(12,70,85,.55),transparent 62%)',
    '--band-bg': '#0d2733',
    '--band-ink': '#f4fafb',
    '--band-ink-soft': '#bed4db',
    '--footer-bg': '#0a1f29',
    '--footer-ink': '#bcd0d8',
    '--footer-head': '#f4fafb',
    '--footer-link': '#78ccdc',
    '--footer-line': 'rgba(255,255,255,.12)',
    '--header-bg': 'rgba(255,255,255,.94)',
    '--demo-bg': '#0a1f29',
    '--demo-ink': '#b5c9d1',
    '--demo-link': '#78ccdc',
  },
  nav: [
    { id: 'services', label: 'Services' },
    { id: 'about', label: 'About' },
    { id: 'visit', label: 'Hours' },
    { id: 'contact', label: 'Book' },
  ],
  order: ['hero', 'strip', 'services', 'about', 'hours', 'contact', 'band'],
  defaults: {
    ctaLabel: 'Request an appointment',
    heroChip: 'Accepting new clients',
    servicesEyebrow: 'How we help',
    servicesTitle: 'Care that starts with listening',
    aboutEyebrow: 'About the practice',
    aboutTitle: 'Straightforward advice, explained plainly.',
    panelTitle: 'Nervous about booking?',
    panelText:
      'Most people are. Tell us that when you get in touch and we’ll take the first visit slowly.',
    hoursEyebrow: 'Visit us',
    hoursTitle: 'Opening hours',
    formTitle: 'Request an appointment',
    formText: 'Leave your details and we’ll call to find a time that works.',
    formButton: 'Request appointment',
    nextTitle: 'What happens next',
    nextSteps: [
      'We call you back to confirm a time',
      'You get a clear idea of cost before anything starts',
      'No pressure, and no jargon',
    ],
    bandTitle: 'Let’s get you booked in.',
    bandText: 'New clients are welcome, and the first conversation is always free.',
  },
};
