/* Retail — shops, boutiques, galleries, florists. Product-led, visit-driven. */
module.exports = {
  key: 'retail',
  label: 'Retail & boutique',
  fonts: 'family=Syne:wght@600;700;800&family=Inter:wght@400;500;600;700',
  tokens: {
    '--font-head': '"Syne",system-ui,sans-serif',
    '--font-body': '"Inter",system-ui,sans-serif',
    '--head-weight': '700',
    '--fs-body': '1.02rem',
    '--bg': '#fbfaf8',
    '--ink': '#33302c',
    '--ink-strong': '#1b1917',
    '--ink-soft': '#514c46',
    '--ink-mute': '#615b54',
    '--accent': '#1f5d54',
    '--accent-hover': '#174841',
    '--accent-ink': '#1b544c',
    '--accent-soft': '#e3efec',
    '--accent-ring': 'rgba(31,93,84,.24)',
    '--on-accent': '#ffffff',
    '--line': '#e6e2dc',
    '--line-strong': '#cec8bf',
    '--card-bg': '#ffffff',
    '--input-bg': '#ffffff',
    '--strip-bg': '#f2efe9',
    '--shadow': '0 16px 42px -24px rgba(27,25,23,.34)',
    '--radius-btn': '4px',
    '--radius-card': '4px',
    '--radius-mark': '4px',
    '--radius-input': '4px',
    '--hero-bg': '#15302c',
    '--hero-ink': '#f6faf8',
    '--hero-ink-soft': '#c4d6d1',
    '--hero-chip': 'rgba(255,255,255,.13)',
    '--hero-chip-ink': '#dcece7',
    '--hero-check': '#7fc0b2',
    '--hero-art':
      'radial-gradient(700px 440px at 86% 10%,rgba(45,120,108,.5),transparent 64%),radial-gradient(480px 340px at 4% 90%,rgba(20,70,63,.55),transparent 62%)',
    '--band-bg': '#15302c',
    '--band-ink': '#f6faf8',
    '--band-ink-soft': '#c4d6d1',
    '--footer-bg': '#1b1917',
    '--footer-ink': '#c8c2ba',
    '--footer-head': '#fbfaf8',
    '--footer-link': '#8fcfc0',
    '--footer-line': 'rgba(255,255,255,.12)',
    '--header-bg': 'rgba(251,250,248,.93)',
    '--demo-bg': '#1b1917',
    '--demo-ink': '#c0bab2',
    '--demo-link': '#8fcfc0',
  },
  nav: [
    { id: 'services', label: 'What we stock' },
    { id: 'about', label: 'Our story' },
    { id: 'visit', label: 'Visit' },
    { id: 'contact', label: 'Enquire' },
  ],
  order: ['hero', 'strip', 'services', 'about', 'hours', 'contact', 'band'],
  defaults: {
    ctaLabel: 'Make an enquiry',
    heroChip: 'Independent & local',
    servicesEyebrow: 'In the shop',
    servicesTitle: 'Chosen by hand, not by algorithm',
    aboutEyebrow: 'Our story',
    aboutTitle: 'A small shop with a long memory.',
    panelTitle: 'Looking for something specific?',
    panelText:
      'Ask us. If we don’t have it we can usually find it, and we’ll tell you honestly if we can’t.',
    hoursEyebrow: 'Come in',
    hoursTitle: 'Opening hours',
    formTitle: 'Ask us anything',
    formText: 'Looking for something particular, or want us to hold an item? Just ask.',
    formButton: 'Send my enquiry',
    nextTitle: 'What happens next',
    nextSteps: [
      'We reply the same day we’re open',
      'We’ll hold anything you ask us to for 48 hours',
      'Collect in store whenever suits you',
    ],
    bandTitle: 'Worth the trip.',
    bandText: 'Come and have a proper look — we’re happy to talk you through anything.',
  },
};
