/* Trades — plumbing, HVAC, electrical, roofing, landscaping.
   Bold, high-trust, phone-first. Every contrast pair verified >= 4.5:1. */
module.exports = {
  key: 'trades',
  label: 'Trades & home services',
  fonts: 'family=Barlow+Condensed:wght@600;700&family=Inter:wght@400;500;600;700;800',
  tokens: {
    '--font-head': '"Barlow Condensed",Impact,sans-serif',
    '--font-body': '"Inter",system-ui,sans-serif',
    '--head-weight': '700',
    '--fs-body': '1.02rem',
    '--bg': '#ffffff',
    '--ink': '#25303d',
    '--ink-strong': '#0f1a26',
    '--ink-soft': '#48566a',
    '--ink-mute': '#5d6b7e',
    '--accent': '#b8430b',
    '--accent-hover': '#963608',
    '--accent-ink': '#a83d0a',
    '--accent-soft': '#fdeee6',
    '--accent-ring': 'rgba(184,67,11,.25)',
    '--on-accent': '#ffffff',
    '--line': '#e2e7ee',
    '--line-strong': '#c8d1dc',
    '--card-bg': '#ffffff',
    '--input-bg': '#ffffff',
    '--strip-bg': '#f5f7fa',
    '--shadow': '0 16px 40px -22px rgba(15,26,38,.4)',
    '--radius-btn': '6px',
    '--radius-card': '10px',
    '--radius-mark': '8px',
    '--radius-input': '6px',
    '--hero-bg': '#0f1f30',
    '--hero-ink': '#ffffff',
    '--hero-ink-soft': '#c3d0de',
    '--hero-chip': 'rgba(255,255,255,.13)',
    '--hero-chip-ink': '#ffffff',
    '--hero-check': '#ff8b45',
    '--hero-art':
      'radial-gradient(700px 400px at 88% 8%,rgba(184,67,11,.5),transparent 62%),linear-gradient(180deg,rgba(255,255,255,.05),transparent)',
    '--band-bg': '#0f1f30',
    '--band-ink': '#ffffff',
    '--band-ink-soft': '#c3d0de',
    '--footer-bg': '#0b1723',
    '--footer-ink': '#c3d0de',
    '--footer-head': '#ffffff',
    '--footer-link': '#ff9d61',
    '--footer-line': 'rgba(255,255,255,.12)',
    '--header-bg': 'rgba(255,255,255,.94)',
    '--demo-bg': '#0b1723',
    '--demo-ink': '#b9c6d4',
    '--demo-link': '#ff9d61',
  },
  nav: [
    { id: 'services', label: 'Services' },
    { id: 'about', label: 'Why us' },
    { id: 'contact', label: 'Get a quote' },
  ],
  order: ['hero', 'strip', 'services', 'about', 'contact', 'band'],
  defaults: {
    ctaLabel: 'Get a free quote',
    heroChip: 'Licensed & insured',
    servicesEyebrow: 'What we do',
    servicesTitle: 'Whatever the job, done right',
    aboutEyebrow: 'Why choose us',
    aboutTitle: 'Straight answers and honest pricing.',
    panelTitle: 'Upfront pricing, every time',
    panelText:
      'You get the price before we start, not after. No call-out surprises, no vague hourly maths.',
    formTitle: 'Request a free quote',
    formText: "Tell us what's going on and we'll get right back to you.",
    formButton: 'Request my quote',
    nextTitle: 'What happens next',
    nextSteps: [
      'We call you back — usually within the hour during business hours',
      'A clear, fixed price before any work starts',
      'Job done, tidied up, and guaranteed',
    ],
    bandTitle: 'Got a problem? Let’s fix it today.',
    bandText: 'Same-day appointments are usually available. One call sorts it.',
  },
};
