/* Wellness — yoga, massage, salon, spa, therapy. Calm, spacious, booking-led. */
module.exports = {
  key: 'wellness',
  label: 'Wellness, salon & studio',
  fonts: 'family=Cormorant+Garamond:wght@500;600&family=Jost:wght@300;400;500;600;700',
  tokens: {
    '--font-head': '"Cormorant Garamond",Georgia,serif',
    '--font-body': '"Jost",system-ui,sans-serif',
    '--head-weight': '600',
    '--fs-body': '1.05rem',
    '--bg': '#f7f6f2',
    '--ink': '#3a3d36',
    '--ink-strong': '#22251f',
    '--ink-soft': '#53574d',
    '--ink-mute': '#5f645a',
    '--accent': '#4a6247',
    '--accent-hover': '#3a4e38',
    '--accent-ink': '#41573e',
    '--accent-soft': '#e6ece3',
    '--accent-ring': 'rgba(74,98,71,.24)',
    '--on-accent': '#ffffff',
    '--line': '#e2e1da',
    '--line-strong': '#cbcabf',
    '--card-bg': '#ffffff',
    '--input-bg': '#ffffff',
    '--strip-bg': '#eeede7',
    '--shadow': '0 18px 44px -26px rgba(34,37,31,.32)',
    '--radius-btn': '999px',
    '--radius-card': '18px',
    '--radius-mark': '50%',
    '--radius-input': '12px',
    '--hero-bg': '#2b332a',
    '--hero-ink': '#f6f7f3',
    '--hero-ink-soft': '#ccd3c8',
    '--hero-chip': 'rgba(255,255,255,.13)',
    '--hero-chip-ink': '#e4ecdf',
    '--hero-check': '#a8c39f',
    '--hero-art':
      'radial-gradient(720px 460px at 82% 14%,rgba(120,150,112,.5),transparent 66%),radial-gradient(520px 360px at 8% 88%,rgba(70,92,66,.55),transparent 64%)',
    '--band-bg': '#2b332a',
    '--band-ink': '#f6f7f3',
    '--band-ink-soft': '#ccd3c8',
    '--footer-bg': '#22251f',
    '--footer-ink': '#c9cfc4',
    '--footer-head': '#f6f7f3',
    '--footer-link': '#b3cca9',
    '--footer-line': 'rgba(255,255,255,.12)',
    '--header-bg': 'rgba(247,246,242,.93)',
    '--demo-bg': '#22251f',
    '--demo-ink': '#c2c8bd',
    '--demo-link': '#b3cca9',
  },
  nav: [
    { id: 'services', label: 'Treatments' },
    { id: 'about', label: 'About' },
    { id: 'visit', label: 'Hours' },
    { id: 'contact', label: 'Book' },
  ],
  order: ['hero', 'strip', 'services', 'about', 'hours', 'contact', 'band'],
  defaults: {
    ctaLabel: 'Book a visit',
    heroChip: 'Now taking bookings',
    servicesEyebrow: 'What we offer',
    servicesTitle: 'Time set aside for you',
    aboutEyebrow: 'About us',
    aboutTitle: 'An unhurried space, run by people who care.',
    panelTitle: 'First time here?',
    panelText:
      'Tell us what you’re after and we’ll match you with the right person and the right amount of time.',
    hoursEyebrow: 'Visit us',
    hoursTitle: 'Opening hours',
    formTitle: 'Book your visit',
    formText: 'Leave your details and we’ll confirm a time that suits you.',
    formButton: 'Request my booking',
    nextTitle: 'What happens next',
    nextSteps: [
      'We call to confirm your time',
      'A short chat about what you need',
      'Arrive a few minutes early and settle in',
    ],
    bandTitle: 'Give yourself the hour.',
    bandText: 'Book now and we’ll take care of the rest.',
  },
};
